### PR TITLE
Env var and filtering keys dynamically 

### PR DESCRIPTION
**Pull request by ehsandanesh**
This change adds the following features to this action to be able to dynamically select specific keys and or iterate through keys in shell scripts.
Following are the two configurations added as optional configurations, and the change is backward compatible.
env-var-prefix
This configuration is optional and is a prefix to the environment variables generated by the action.
For example, if the dot notation key in the output is like a.b.c.d.x and the value for this config is myVars, then the environment variable set by the action will be like myVars_a_b_c_d_x .
key-path-pattern
This configuration is optional and is a regular expression that filters out keys that match the pattern.
It also removes that pattern from the key string if the dot notation key is like a.b.c.d.x and the key-path-pattern is ^a\.b\. The output key will be c.d.x .

### CODE REVIEW

**Comment by pietrobolcato** [comment]
Thank you for the PR @ehsandanesh! Will check it latest on the weekend, will get back to you soon!

**Comment by ehsandanesh** [comment]
@pietrobolcato, any update on this PR?

**Comment by ehsandanesh** [comment]
@pietrobolcato, I would really appreciate it if you give an update about this PR. It sits idle for a very long time.

**Comment by pietrobolcato** [comment]
sorry for the delay, was not getting notifications somehow - thanks for the contribution! merged now!

**Pull request merged**
